### ISSUE TITLE
Support nameko 3

### ISSUE THREAD

**Issue by zsiciarz** [Emplocity/nameko-prometheus#10]
Version 3 has been a RC for quite a long time now. We should support services built with nameko 3. However it is not a goal for nameko-prometheus 1.0.

**Comment by aguiot** [comment]
Hi,

I'm using nameko-rc.3, and would like to use nameko-prometheus.
Do you plan to support nameko-3 soon?

**Comment by zsiciarz** [comment]
Hi Anthony,
As of right now, none of us in the team behind nameko-prometheus has had any experience with nameko 3 yet. Therefore we didn't intend to support it from the beginning. However if there is interest in the community, we'll see what we can do. In the meantime we're open to contributions :-)

**Comment by alfaro28** [comment]
Hi, I did a very light test with nameko 3 and seems to work fine, any specific reason to disable it? or is just a precaution as is not tested?

**Comment by zsiciarz** [comment]
We've just released 1.4.0 with support for nameko 3.0 RC.
