### ISSUE TITLE
Add ability for ignore some RPC or add support for nameko timer

### ISSUE THREAD

**Issue by urtow** [Emplocity/nameko-prometheus#18]
Hello!
Thanks for great package!

Please add support for nameko timer - https://nameko.readthedocs.io/en/stable/built_in_extensions.html#timer

Or add parameter for ignore getting metrics from some methods

**Comment by zsiciarz** [comment]
Hi there,
We've just released 1.6.0 to PyPI with support for `Timer` and `Consumer` entrypoints.
